// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeAPI.Data;

#nullable disable

namespace ProgettoPokemon.Migrations
{
    [DbContext(typeof(PokeDbContext))]
    [Migration("20250302220744_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PokeAPI.Model.Attack", b =>
                {
                    b.Property<int>("AttackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AttackId"));

                    b.Property<int?>("ConvertedEnergyCost")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Cost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Damage")
                        .HasColumnType("longtext");

                    b.Property<int>("DatasId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("AttackId");

                    b.HasIndex("DatasId");

                    b.ToTable("attacks");
                });

            modelBuilder.Entity("PokeAPI.Model.Datas", b =>
                {
                    b.Property<int>("DatasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DatasId"));

                    b.Property<string>("Artist")
                        .HasColumnType("longtext");

                    b.Property<int?>("ConvertedRetreatCost")
                        .HasColumnType("int");

                    b.Property<string>("Hp")
                        .HasColumnType("longtext");

                    b.Property<int?>("ImagesId")
                        .HasColumnType("int");

                    b.Property<int?>("LegalitiesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .HasColumnType("longtext");

                    b.Property<string>("Rarity")
                        .HasColumnType("longtext");

                    b.Property<int?>("SetId")
                        .HasColumnType("int");

                    b.Property<string>("Supertype")
                        .HasColumnType("longtext");

                    b.Property<int?>("TcgplayerId")
                        .HasColumnType("int");

                    b.HasKey("DatasId");

                    b.HasIndex("ImagesId");

                    b.HasIndex("LegalitiesId");

                    b.HasIndex("SetId");

                    b.HasIndex("TcgplayerId");

                    b.ToTable("datas");
                });

            modelBuilder.Entity("PokeAPI.Model.Holofoil", b =>
                {
                    b.Property<int>("HolofoilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HolofoilId"));

                    b.Property<double?>("DirectLow")
                        .HasColumnType("double");

                    b.Property<double?>("High")
                        .HasColumnType("double");

                    b.Property<double?>("Low")
                        .HasColumnType("double");

                    b.Property<double?>("Market")
                        .HasColumnType("double");

                    b.Property<double?>("Mid")
                        .HasColumnType("double");

                    b.Property<int?>("PricesId")
                        .HasColumnType("int");

                    b.HasKey("HolofoilId");

                    b.HasIndex("PricesId")
                        .IsUnique();

                    b.ToTable("holofoils");
                });

            modelBuilder.Entity("PokeAPI.Model.Images", b =>
                {
                    b.Property<int>("ImagesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ImagesId"));

                    b.Property<string>("Large")
                        .HasColumnType("longtext");

                    b.Property<string>("Logo")
                        .HasColumnType("longtext");

                    b.Property<string>("Small")
                        .HasColumnType("longtext");

                    b.Property<string>("Symbol")
                        .HasColumnType("longtext");

                    b.HasKey("ImagesId");

                    b.ToTable("images");
                });

            modelBuilder.Entity("PokeAPI.Model.Legalities", b =>
                {
                    b.Property<int>("LegalitiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LegalitiesId"));

                    b.Property<string>("Expanded")
                        .HasColumnType("longtext");

                    b.Property<string>("Unlimited")
                        .HasColumnType("longtext");

                    b.HasKey("LegalitiesId");

                    b.ToTable("legalities");
                });

            modelBuilder.Entity("PokeAPI.Model.Prices", b =>
                {
                    b.Property<int>("PricesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PricesId"));

                    b.HasKey("PricesId");

                    b.ToTable("prices");
                });

            modelBuilder.Entity("PokeAPI.Model.Set", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SetId"));

                    b.Property<string>("Identificatore")
                        .HasColumnType("longtext");

                    b.Property<int?>("ImagesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("PrintedTotal")
                        .HasColumnType("int");

                    b.Property<string>("PtcgoCode")
                        .HasColumnType("longtext");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("longtext");

                    b.Property<string>("Series")
                        .HasColumnType("longtext");

                    b.Property<int?>("Total")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("longtext");

                    b.HasKey("SetId");

                    b.HasIndex("ImagesId");

                    b.ToTable("sets");
                });

            modelBuilder.Entity("PokeAPI.Model.Tcgplayer", b =>
                {
                    b.Property<int>("TcgplayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TcgplayerId"));

                    b.Property<int?>("PricesId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("TcgplayerId");

                    b.HasIndex("PricesId");

                    b.ToTable("tcgplayers");
                });

            modelBuilder.Entity("PokeAPI.Model.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("utenti");
                });

            modelBuilder.Entity("PokeAPI.Model.Weakness", b =>
                {
                    b.Property<int>("WeaknessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WeaknessId"));

                    b.Property<int>("DatasId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("WeaknessId");

                    b.HasIndex("DatasId");

                    b.ToTable("weaknesses");
                });

            modelBuilder.Entity("PokeAPI.Model.Attack", b =>
                {
                    b.HasOne("PokeAPI.Model.Datas", "Datas")
                        .WithMany("Attacks")
                        .HasForeignKey("DatasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datas");
                });

            modelBuilder.Entity("PokeAPI.Model.Datas", b =>
                {
                    b.HasOne("PokeAPI.Model.Images", "Images")
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokeAPI.Model.Legalities", "Legalities")
                        .WithMany()
                        .HasForeignKey("LegalitiesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokeAPI.Model.Set", "Set")
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokeAPI.Model.Tcgplayer", "Tcgplayer")
                        .WithMany()
                        .HasForeignKey("TcgplayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Images");

                    b.Navigation("Legalities");

                    b.Navigation("Set");

                    b.Navigation("Tcgplayer");
                });

            modelBuilder.Entity("PokeAPI.Model.Holofoil", b =>
                {
                    b.HasOne("PokeAPI.Model.Prices", "Prices")
                        .WithOne("Holofoil")
                        .HasForeignKey("PokeAPI.Model.Holofoil", "PricesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("PokeAPI.Model.Set", b =>
                {
                    b.HasOne("PokeAPI.Model.Images", "Images")
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Images");
                });

            modelBuilder.Entity("PokeAPI.Model.Tcgplayer", b =>
                {
                    b.HasOne("PokeAPI.Model.Prices", "Prices")
                        .WithMany()
                        .HasForeignKey("PricesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("PokeAPI.Model.Weakness", b =>
                {
                    b.HasOne("PokeAPI.Model.Datas", "Datas")
                        .WithMany("Weaknesses")
                        .HasForeignKey("DatasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datas");
                });

            modelBuilder.Entity("PokeAPI.Model.Datas", b =>
                {
                    b.Navigation("Attacks");

                    b.Navigation("Weaknesses");
                });

            modelBuilder.Entity("PokeAPI.Model.Prices", b =>
                {
                    b.Navigation("Holofoil");
                });
#pragma warning restore 612, 618
        }
    }
}
